version: '{build}'

image: Visual Studio 2019

configuration: Release

branches:
  except:
    - gh-pages

install:
  - ps: $last_tag = git describe --tags --abbrev=0
  - ps: $count_commits = git rev-list --count "${last_tag}..HEAD"
  - ps: $commit_hash = git rev-parse --short HEAD
  - ps: $dirty = if (git describe --tags --dirty | %{$_ -match ".*-dirty$"}) { echo "-dirty" } else { echo "" }
  - ps: $delm = if ($last_tag -match ".*-.*") { echo "." } else { echo "-" }
  - ps: $version = "${last_tag}${delm}${count_commits}.${commit_hash}${dirty}"
  - ps: Update-AppveyorBuild -Version "${version}+$env:APPVEYOR_BUILD_NUMBER"

build_script:
- cmd: cmake -B build -DCMAKE_BUILD_TYPE=%CONFIGURATION% C:\projects\semver
- cmd: cmake --build build --config %CONFIGURATION%

test_script:
- cmd: build\%CONFIGURATION%\testrunner.exe --gtest_output="xml:build\test_report.xml"

after_test:
- ps: |
    # example from: https://www.appveyor.com/docs/running-tests/#pushing-real-time-test-results-to-build-console
    # upload results to AppVeyor
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path build\test_report.xml))

artifacts:
- path: build\test_report.xml
  name: test_report

