.build_template: &build_definition
  script:
    - .gitlab-ci/gitlab-build.sh

build:gcc-10.1.0:
  variables:
    COMPILER: gcc-10.1.0
    BUILD_TYPE: Release
    GTEST_COLOR: 1
  image: mariokonrad/marnav:${COMPILER}
  <<: *build_definition

