.build_template: &build_definition
  script:
    - .gitlab-ci/gitlab-build.sh
    - tests/test_subdirectory.sh
    - tests/test_fetchcontent.sh

build:gcc-10.2.0:
  variables:
    COMPILER: gcc-10.2.0
    BUILD_TYPE: Release
    GTEST_COLOR: 1
  image: mariokonrad/marnav:${COMPILER}
  <<: *build_definition

